version: '3'
services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: girls_db
      PGDATA: ${POSTGRES_PGDATA}
    volumes:
      - ./db/dev:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      localnet:
        ipv4_address: ${DB_ADDRESS}
  db-ui:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      localnet:
        ipv4_address: ${ADMIN_ADDRESS}

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_NETWORK}
          gateway: ${GATEWAY_NETWORK}

    
